### ISSUE TITLE
[EPIC] Better implementation for Lenra Forms

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/Lenra#122]
# Flutter forms to Lenra forms

## How to do it in Flutter

Use the Form component with a GlobalKey to keep a reference to it for child formfields. This will ensure that all of the form fields that are children to this Form are grouped together and will be validated and sent together.

There is a way to avoid using a `GlobalKey` but it does not seem to be useful in our case. Here is the link to the documentation for this just in case [Form.of](https://api.flutter.dev/flutter/widgets/Form/of.html).

```dart
final _formKey = GlobalKey<FormState>();

Form(
    key: _formKey,
    child: buildChildrenFormFields(),
)
```

Then we need to define one or more `FormField`s inside of the `Form` widget. In this example we will use two `TextFormField` widgets that implements the `FormField` class.

```dart
Column buildChildrenFormFields() {
    return Column(
        children: [
            TextFormField(
                validator: (value) {
                    if (value == null || value.isEmpty) {
                        return 'Please enter some text.';
                    }
                    return null;
                },
            ),
            TextFormField(
                validator: (value) {
                    if (value.length > 10) {
                        return 'Cannot be longer than 10 characters.';
                    }
                    return null;
                },
            ),
        ]
    );
}
```

Add a button to validate and send the form.

```dart
TextButton(
    child: Text('Submit'),
    onPressed: () {
        // Make sure that the form values are valid before sending it.
        if(_formKey.currentState!.validate()) {
            sendForm();
        }
    }
)
```

## How to use `Form` in Lenra apps

We could implement our form components by following the principle of the following repository.
 
https://github.com/flutter-form-builder-ecosystem/flutter_form_builder

The way it works is by adding a `name` property to each `FormField` component implementation and adding a getter inside of the `FormState` to get all of the values for a `Form`. This simplifies a lot the process of getting the values of each element of the `Form`.

### Example

Define two form fields with a name.

```dart
FormBuilderTextField(name: 'field1')
FormBuilderTextField(name: 'field2')
```

Call the `FormState` to get the values 

```dart
_formKey.currentState?.value;
```

This will return value in this format

```json
{
    "field1": "value of field1",
    "field2": "value of field2"
}
```

This seems to be quite simple to implement, the only hard part would be to make sure that the `FormState` is properly linked to the values and can get them at any time. The library seems to be regularly kept up to date so we could use it as is. The only problem using this library is that we would need to implement new Lenra components using the form fields provided by the library, so in case we needed to get rid of it, it would be a lot of work to change the components implementation.

**Comment by jonas-martinez** [comment]
@lenra-io/devs I'm still thinking about the best way to do it so new information might come soon. For the moment, do you have anything to add for the lenra form implementation?

**Comment by jonas-martinez** [comment]
I didn't see that Nesqwik already opened a discussion for this subject, https://github.com/lenra-io/Lenra/discussions/120

**Comment by Nesqwik** [comment]
The Form issue is open here https://github.com/lenra-io/lenra_ui_runner/issues/166 
It's coming from the discussion https://github.com/lenra-io/Lenra/discussions/120

I'm closing this Epic to avoid duplicate :)
