### ISSUE TITLE
Ask for CGU on subscribe

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#13]
The goal is to create a CGU system to ensure that all user accept the CGU on subscribtion.
- A CGU is a markdown file statically transformed into a HTML version.
- These files will be stored into the static file of the server. (priv/static)
- We will add a CGU table in the database to store the link of the file + id + version + hash of the file
- A user will accept a specific version of the CGU on subscribtion (and will have to accept all the changes after that)
- We will store in the database which versionS of the CGU a user did accept.
- The Hash of the file ensure that the file cannot be changed at all.

Server : 
- https://github.com/lenra-io/server/issues/84
- https://github.com/lenra-io/server/issues/83
- https://github.com/lenra-io/server/issues/96
- https://github.com/lenra-io/server/issues/85
- https://github.com/lenra-io/server/issues/86
- https://github.com/lenra-io/server/issues/87
- https://github.com/lenra-io/server/issues/88
- https://github.com/lenra-io/server/issues/89

Client : 
- https://github.com/lenra-io/client/issues/59
- https://github.com/lenra-io/client/issues/58

**Comment by ClementGld** [comment]
In this issue : - https://github.com/lenra-io/server/issues/89 
I'm making a pull request to update the register API but we think we need to add CGU acceptance outside of registration. So after the registration or Login, the server send an access token with a parameter cgu_is_accept true or false(for example) and if it's false we have to send the latest CGU and the user have to accept it. If it's true the user can go to the home page.
We also have to add, in the cguService something to check if the user have accepted the cgu.
This can help us later implement the cgu update system more easily.

At the level of this epic I have advanced to the last issue of the server and it remains the last issue of the client normally
