### ISSUE TITLE
Manage the dev-tools hot reload by the server

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#23]
Make the devtool server watch the function directory (as explain here https://hostiledeveloper.com/2016/02/24/hey-watch-it-or-how-to-monitor-files-in-elixir.html) to make it restart the app.

A build environment variable can be defined to build the app when server starts and when there is a change in the function directory.

In of-watchdog HTTP mode, the server si stopped before the build and restarted after it.

- https://github.com/lenra-io/dev-tools/issues/68
- https://github.com/lenra-io/dev-tools/issues/69
- https://github.com/lenra-io/dev-tools/issues/70
- https://github.com/lenra-io/dev-tools/issues/71
- https://github.com/lenra-io/dev-tools/issues/72

**Comment by jonas-martinez** [comment]
This will be handled by this Epic : https://github.com/lenra-io/Lenra/issues/144
