### ISSUE TITLE
Change the way we handle emails to match language

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/Lenra#31]
We want to change the way we handle emails to match the language of the user.

This could be done on SendGrid by having a template for the style as we do actually but also use a template for the language. This would make the server cleaner.

- https://github.com/lenra-io/server/issues/202
- https://github.com/lenra-io/client/issues/135

**Comment by Nesqwik** [comment]
@jonas-martinez is this epic done ?

**Comment by jonas-martinez** [comment]
Yes ! :)
