### ISSUE TITLE
Handle app settings management

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/Lenra#33]
We want to give more control over applications. 

It should be possible to
- https://github.com/lenra-io/client/issues/137
- https://github.com/lenra-io/client/issues/136
- https://github.com/lenra-io/client/issues/138
- https://github.com/lenra-io/server/issues/203
- https://github.com/lenra-io/server/issues/204
- https://github.com/lenra-io/server/issues/205

More work : 
- https://github.com/lenra-io/server/pull/206

**Comment by jonas-martinez** [comment]
Work will also need to be done on the https://gitlab.com/lenra/platform/lenra-ci repository to handle branch and credentials.

- Clone repository from `branch` with `credentials`

Some help on the `branch` : https://stackoverflow.com/questions/1778088/how-do-i-clone-a-single-branch-in-git
which says that it is possible to clone only one branch with : `git clone <url> --branch <branch> --single-branch`

Some help on the `credentials` : TODO

**Comment by jonas-martinez** [comment]
For issue https://github.com/lenra-io/client/issues/137, I need to be able to get the `repository` field from the `application`. The problem is, if I add the repository to the JSON response on the server, anyone who has access to the application could see the repository url containing the credentials of the app admin.

This implies that we need to handle repository link read access so that only the admin (and moderators + some others ?) could get the `repository` field from the JSON response

**Comment by Nesqwik** [comment]
@jonas-martinez is this epic done ?

**Comment by jonas-martinez** [comment]
Yes !
