### ISSUE TITLE
[EPIC] Make Lenra app protocol non-sync

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#89]
## Current behavior 
Currently Lenra hash the action/props tuple to a "code" and send the code to the client.
The server store the action/props tuple to get it back later.
The client send back the code to the server when the action is performed.
The server transform the code back to the action/props tuple then run the listener.

Pros : 
- The client cannot see the data in the props in case of the dev sent sensible data.
- Generally less data transfered between client and server

Cons :
- More complexity
- More server-side cache (more RAM used by the server)
- If the SessionManager crash, it losses the action/props map and cannot send react to a user action.

## Possible solution : 
Remove the code and send action/props to the client.
The pro/cons are reversed but to balance the new cons : 
- Limit the size of the props to only allow a few ids/consts
- Warn the developper to avoid passing important data (only ids) into props.

This is not a perfect solution. Any ideas ? @lenra-io/devs

**Comment by shiipou** [comment]
I think the new action/props will be better, and I think the cons to limit the size to few ids/consts is not a real case.
In normal use of Lenra, you didn't use it in an other way than. More complexe data will always be stored in datastores and retrieve with a query.

**Comment by taorepoara** [comment]
@Nesqwik I think we can close this one. Don't you think ?

**Comment by Nesqwik** [comment]
Sure.
The protocol is still synchronised but it is necessary to ensure that a listener cannot be called by any other user than the user that received it.

This huge layer of security can justify the downside of a synchronised protocol IMO.
