### ISSUE TITLE
[EPIC] Generic Template (use any language)

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#94]
The generic template could be done by starting a docker image containing the app of the user.

For the devtool, start the "main" devtool image that will start : 
- The "server" and the "client" to run the app
- The docker image containing the app
- The postgres image containing the database

For the server : 
- Build the docker image using simply the provided Dockerfile
- Run the builded docker image as an app

The dev must follow the I/O rules and return the correct answer.

Any other ideas @lenra-io/devs ? @taorepoara & @shiipou you had an idea around this involving the docker socket or docker-compose, could you explain the idea ? 

Note : If done correctly, isn't this could be the default "template" ? 
Then we only need to provide  the Dockerfile and the base hello-world template for all language/framework.

**Comment by taorepoara** [comment]
The new template is handled by the [lenra CLI](https://github.com/lenra-io/lenra_cli). Two templates (rust and node) are almost ready. We are waiting for Mongo to open their sources.
